@startuml "First implementation"

participant "NRF24 A" as nrfA
participant "NRF24 B" as nrfB

loop until package arives
nrfA -x nrfB : send update of led
nrfA -> nrfB : send update of led
nrfB -x nrfA : send acknowledgement
nrfA -> nrfB : send update of led
nrfB -> nrfA : send acknowledgement
end

@enduml