@startuml

participant "NRF24 A" as nrfA
participant "NRF24 B" as nrfB

nrfA -> nrfB : Send led update
nrfB -> nrfA : Received led update (Acknowledgement)
nrfB -> nrfB : check if we wrote bytes
nrfB -> nrfB : if we wrote bytes update led
nrfA -> nrfA : if received led uppdate returned the same number turn on led


@enduml